### ISSUE TITLE
Run automatically

### ISSUE THREAD

**Issue by alejandroaasc** [CoolerVoid/codewarrior#13]
Hello everyone,
Thanks in advance for this important project, I have a doubt about this tool, if I need to run this tool over a DD, what could be the best practice? is it possible to run it from a script? 
PD: my dd has a source code of my application with a lot of folders.

Thanks again...

**Comment by CoolerVoid** [comment]
Hello, thank you !

This tool is cool to manual analysis, because is not have intelligent logic to search bugs, uses only regex, and you look the important chunks of code to search common bugs...

If you need automatic process in console mode, look this project: https://github.com/CoolerVoid/Mosca

This other project uses taint analysis, but works only in C++:
https://github.com/CoolerVoid/heap_detective
