### ISSUE TITLE
fatal error: 'openssl/ssl.h' file not found

### ISSUE THREAD

**Issue by infomaven** [CoolerVoid/codewarrior#14]
I'm seeing an error when I try to build CodeWarrior on Mac Mohave.  
What do you advise to fix this? 

input:
$ make
 
output: 
Compile... 
gcc -Wall -Wextra   -DMG_ENABLE_SSL -DMG_DISABLE_PFS lib/slre/slre.c lib/libmongoose/mongoose.c lib/sha256/sha256.c lib/BSD/strsec.c lib/frozen/frozen.c  -c src/*.c 
lib/libmongoose/mongoose.c:4658:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [warrior] Error 1

**Comment by CoolerVoid** [comment]
You need to install openssl library...
Please search in your mac ports.

**Comment by viable-hartman** [comment]
So there is a bit more to this than just installing the library on MacOS.  Below are the steps.

_I use brew instead of MacPorts, but the steps should be similar_

# Install openssl

        brew install openssl

# Find out where openssl installed to by running

        brew info openssl

You will see something like:

> For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

> For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

# Set your environment variables for compilation as directed in the above output

        LD_LIBRARY_PATH=/usr/local/opt/openssl@1.1/lib:"${LD_LIBRARY_PATH}"
        CPATH=/usr/local/opt/openssl@1.1/include:"${CPATH}"
        PKG_CONFIG_PATH=/usr/local/opt/openssl@1.1/lib/pkgconfig:"${PKG_CONFIG_PATH}"
        export LD_LIBRARY_PATH CPATH PKG_CONFIG_PATH

# Utilizing pkg-config, find out what LDFLAGS to include

        pkg-config openssl --libs

> -L/usr/local/Cellar/openssl@1.1/1.1.1d/lib -lssl -lcrypto

# Now I edit my Make file to include the LDFLAGS output above

        vi Makefile
        # Change the below line to the one below it (I just comment it out)
        #LDFLAGS=-lpthread -lcrypto -lssl
        LDFLAGS=-lpthread -L/usr/local/Cellar/openssl@1.1/1.1.1d/lib -lssl -lcrypto

# Make it again
Now *make* should work on MacOS

        make

**Comment by CoolerVoid** [comment]
Occasionally an update of XCode or MacOS will cause the linker to fail after compilation, to rectify this you may want to try and run:
```xcode-select --install```
If Homebrew is installed to the default location of /usr/local, OpenSSL will be automatically detected.

Other path to try is use ports and find other package like libssl.
```
$ sudo port install openssl
or
$ sudo port install libssl
```
Reference:
https://www.macports.org/install.php

**Comment by Yashvendra** [comment]
Hi Guys, 

I'm on a linux OS, facing the same issue: 
<img width="911" alt="code" src="https://user-images.githubusercontent.com/23001311/88946283-aa348d00-d2ac-11ea-9416-7d039cf89cfb.PNG">

My openssl is installed @ `/usr/bin/openssl`.

Can someone share thoughts to resolve this ??

Thanks.

**Comment by CoolerVoid** [comment]
follow commands to try solve...

RPM based linux:
```

 yum install openssl–devel
````

On debian based like ubuntu:
```
apt-get install libssl-dev
```
This error is common if you dont have openssl lib...

**Comment by Huixxi** [comment]
https://stackoverflow.com/questions/42044221/openssl-not-found-on-macos-sierra  I solved.
